kind: Service
apiVersion: v1
metadata:
  name: search-service
spec:
  type: NodePort
  selector:
    app: search-service
  ports:
  - protocol: TCP
    port: 8090
    nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-deployment
  labels:
    app: search-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-servicee
        image: satyendrasingh/search:0.$BUILD_NUMBER
        ports:
        - containerPort: 8090

---

kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq-service
  ports:
  - protocol: TCP
    port: 5672
    nodePort: 30100

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-service-deployment
  labels:
    app: rabbitmq-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq-service
  template:
    metadata:
      labels:
        app: rabbitmq-service
    spec:
      containers:
      - name: rabbitmq-servicee
        image: rabbitmq
        ports:
        - containerPort: 5672
